name: Test the docker workflows

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  BuildandPush:
    uses: ./.github/workflows/docker-push.yaml
    with:
      AWSRoleToAssume: arn:aws:iam::916080180725:root
      AWSRegion: us-east-1
      dockerFilePath: Dockerfile
      ecrHost: 916080180725.dkr.ecr.us-east-1.amazonaws.com
      ecrName: diliptest
  PullandPush:
    needs: BuildandPush
    uses: ./.github/workflows/docker-pull-retag.yaml
    with:
      AWSRoleToAssume: arn:aws:iam::916080180725:root
      AWSRegion: us-east-1
      fromecrHost: 916080180725.dkr.ecr.us-east-1.amazonaws.com
      toecrHost: 916080180725.dkr.ecr.us-east-1.amazonaws.com
      ecrName: diliptest