name: Docker push and ReTag
on:
  workflow_call:
    inputs:
      AWSRoleToAssume:
        required: true 
        description: IAM Role to use 
      AWSRegion:
        default: us-east-2 
        description: path to Docker file
      toEcrHost:
        description: ECR hostname
        required: true
      ecrName:
        required: true
        description: name of ecr
      fromecrHost:
        description: ECR hostname
        required: true

      
jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.AWSRoleToAssume }}
          aws-region: ${{ inputs.AWSRegion }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: dockerBuild
        run: docker pull ${{inputs.fromecrHost}}/${{inputs.ecrName}}

      - name: dockerPush
        run: docker push ${{inputs.ecrHost}}/${{inputs.ecrName}}