name: Docker Push
on:
  workflow_call:
    inputs:
      AWSRoleToAssume:
        required: true 
        description: IAM Role to use 
        type: string
      AWSRegion:
        default: us-east-2 
        description: path to Docker file
        type: string
      dockerFilePath:
        required: true 
        description: path to Docker file
        type: string
      ecrHost:
         description: ECR hostname
         required: true
         type: string
      ecrName:
         required: true
         description: name of ecr
         type: string
      # nugetToken:
      #    description: Nuget auth Token
      #    required: true
      
jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.AWSRoleToAssume }}
          aws-region: ${{ inputs.AWSRegion }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: dockerBuild
        run: docker build -t ${{inputs.ecrHost}}/${{inputs.ecrName}} .

      - name: dockerPush
        run: docker push ${{inputs.ecrHost}}/${{inputs.ecrName}}