name: Docker push and ReTag
on:
  workflow_call:
    inputs:
      AWSRoleToAssume:
        required: true 
        description: IAM Role to use 
        type: string
      AWSRegion:
        default: us-east-2 
        description: path to Docker file
        type: string
      toEcrHost:
        description: ECR hostname
        required: true
        type: string
      ecrName:
        required: true
        description: name of ecr
        type: string
      fromecrHost:
        description: ECR hostname
        required: true
        type: string

      
jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.AWSRoleToAssume }}
          aws-region: ${{ inputs.AWSRegion }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: dockerpull
        run: docker pull ${{inputs.fromecrHost}}/${{inputs.ecrName}}

      - name: dockerReTag
        run: docker tag ${{inputs.fromecrHost}}/${{inputs.ecrName}} ${{inputs.toecrHost}}/${{inputs.ecrName}}

      - name: dockerpushTaggedimage
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
          docker_username: AWS
          docker_password: ${{inputs.toecrHost}}
        run: |
          docker push ${{inputs.toecrHost}}/${{inputs.ecrName}}